// This is a function that will be called when the page is loaded
// This file contains code generated by GitHub co-pilot


// Return the current time
function getTime() {
    return new Date().toLocaleTimeString();
}

// find all images without alternate text
// and give them a red border
function process() {
    var images = document.getElementsByTagName("img");
    for (var i = 0; i < images.length; i++) {
        var img = images[i];
        if (img.alt == "") {
            img.style.border = "2px solid red";
        }
    }
}


function calculateDaysBetweenDates(begin, end) {
    var oneDay = 24 * 60 * 60 * 1000;
    var firstDate = new Date(begin);
    var secondDate = new Date(end);
    return Math.round(Math.abs((firstDate.getTime() - secondDate.getTime()) / (oneDay)));
}


// Express server on port 3000
var express = require('express');
var app = express();
var server = app.listen(3000);


// if statement to check if the user is logged in
if (document.cookie.indexOf("user=") == -1) {
    window.location.href = "login.html";
}